<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('users')->delete();

        \DB::table('users')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Selina Ahmed',
                'email' => 'salina.pervez@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$.3MZImlq8Q1PNEURn.xikeRI3q4eXJ2lMw76vE04PJi45h6zq5Zcy',
                'is_special' => 0,
                'remember_token' => 'doPouS0DD0kmC683IMhpKwDRQmqc9KPW46rViTkYFiEYq113FMJvfXmwLfKJ',
                'created_at' => '2019-08-27 16:35:38',
                'updated_at' => '2019-08-29 12:14:39',
                'username' => 'admin',
                'user_type' => 'Employee',
                'mobile' => '01726731208',
                'reference_table_id' => 2,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-08-27 16:42:11',
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Golam Mohammad Bhuaia',
                'email' => 'gmb@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CtuL1cKjVUXPqH4RQpFRBOYyzQsDMrbEgeMJcks6jHW/N8o7KZoLW',
                'is_special' => 0,
                'remember_token' => 'svtG4OS5tuXIaPjz5yGCnuHOfpJKKspMEbyiKHp0ixsPccA28MVLqpDt0qI1',
                'created_at' => '2019-08-27 16:37:08',
                'updated_at' => '2019-08-29 12:16:54',
                'username' => 'DS1',
                'user_type' => 'Employee',
                'mobile' => '01716094068',
                'reference_table_id' => 3,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-08-27 16:44:07',
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'Fakhar Uddin Ahmed',
                'email' => 'shakhsadee@hotmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$1LTXnjeFWP1W8YFfnesjqOHT4LBetFFa.WzIT.G4I2h9qrmjKRDGC',
                'is_special' => 0,
                'remember_token' => 'GcU9xIx9KuHEreOimoLo7W4srB9ObUo1dr5AifVapXQ2R3GWfkWwuYYOV881',
                'created_at' => '2019-08-27 16:38:26',
                'updated_at' => '2019-08-29 12:22:21',
                'username' => 'AO1',
                'user_type' => 'Employee',
                'mobile' => '01670688668',
                'reference_table_id' => 4,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-08-27 16:44:41',
            ),
            3 =>
            array (
                'id' => 5,
                'name' => 'Md. Nabir Uddin',
                'email' => 'nobir@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$NBVWXyXphbfWNbk7yoK6puy5PaPKXxYcDFR4I2v0VTcmYJ/Z6WEzy',
                'is_special' => 0,
                'remember_token' => 'qXr8aSuHJQOHd4qITbMhq7hgscUtwrt1XZGazjeVTV6ivZ46j89BvBZ2MRIm',
                'created_at' => '2019-08-27 18:59:27',
                'updated_at' => '2019-08-29 12:28:42',
                'username' => 'ME1',
                'user_type' => 'Employee',
                'mobile' => '01717178030',
                'reference_table_id' => 5,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-08-27 18:59:58',
            ),
            4 =>
            array (
                'id' => 6,
                'name' => 'Md. Khairul Amin',
                'email' => 'khairul.amin@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$/uY1AsMVOUCDoAVZFGOwRezPn3keOSj4WVfbbw6taphgLHEMIzaWe',
                'is_special' => 0,
                'remember_token' => 'PkePtS7OQiE6LlEYzpoQkbgAbO6Z0jqqhpkHPzCQkNUOEHnM75gw3Ql2UJcv',
                'created_at' => '2019-09-11 14:34:40',
                'updated_at' => '2019-09-11 16:18:06',
                'username' => 'J.S.1',
                'user_type' => 'Employee',
                'mobile' => '01727674265',
                'reference_table_id' => 6,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-11 16:18:06',
            ),
            5 =>
            array (
                'id' => 7,
                'name' => 'Md.Saarker Alam',
                'email' => 'ssarker@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$pnA7KOMbixMW8lzTpAFaf.KtXWhF/rwsnLI/vuLKuqP446TdtuE.G',
                'is_special' => 0,
                'remember_token' => 'e0eanPS3lWyae2nn5dda4FpbBJ8vL4mqFH4AGXY0snxrUqOtnvDoEsDMyYDd',
                'created_at' => '2019-09-11 14:40:01',
                'updated_at' => '2020-01-06 16:03:52',
                'username' => 'J.S.2',
                'user_type' => 'Employee',
                'mobile' => '01550150635',
                'reference_table_id' => 7,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2020-01-06 16:03:52',
            ),
            6 =>
            array (
                'id' => 8,
                'name' => 'Md.Amzad Ahmed Bapari',
                'email' => 'amjadbapari@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$B01p595DLstCMcT7hbHSy.8Qw1iu0p0sY47CByVnizJoO4r.WVkBi',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-11 14:43:14',
                'updated_at' => '2019-09-11 14:43:14',
                'username' => 'J.S.3',
                'user_type' => 'Employee',
                'mobile' => '01711909766',
                'reference_table_id' => 8,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            7 =>
            array (
                'id' => 9,
                'name' => 'Ahesanul Parvez',
                'email' => 'parvez770@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$jIPbM8MYRHfhFjtBA.kPa.WpNZ3eozYkKyLmj5Y9lLiphYiVjRqBO',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-11 14:45:59',
                'updated_at' => '2019-09-11 14:45:59',
                'username' => 'J.S.4',
                'user_type' => 'Employee',
                'mobile' => '01715087778',
                'reference_table_id' => 9,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            8 =>
            array (
                'id' => 10,
                'name' => 'Mehedi Hasan',
                'email' => 'mehedi@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$0XULez8TTZB1bRpLeSXq/eVTTDHRkCVIX6vlLT5upy3drIww4lfcS',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-11 14:54:42',
                'updated_at' => '2019-09-11 14:54:42',
                'username' => 'D.S.2',
                'user_type' => 'Employee',
                'mobile' => '01552476487',
                'reference_table_id' => 10,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            9 =>
            array (
                'id' => 11,
                'name' => 'Moynul Bhuaiya',
                'email' => 'moynul@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$BCPs/nqbAJwx/lhquX5iTO4c1mAgPW0ZkwpnNRhHPWgzYfBGvMW7a',
                'is_special' => 0,
                'remember_token' => '7xduU0LDtNcSBFG940Odrw4CAOfjDcuOMCf2pi1EzwCsHeA869xNwKgzDq2y',
                'created_at' => '2019-09-11 15:03:05',
                'updated_at' => '2019-09-11 17:25:00',
                'username' => 'D.S.3',
                'user_type' => 'Employee',
                'mobile' => '01711385917',
                'reference_table_id' => 11,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-11 17:25:00',
            ),
            10 =>
            array (
                'id' => 12,
                'name' => 'Md Monirul Islam ',
                'email' => 'monirul@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$FE/y0r1gI9RmeHbBVofTsevGmwD0mDAA4ja.tnnSjj3AlXwkU7Ipa',
                'is_special' => 0,
                'remember_token' => '6O4GJDWpNKkOxpGzG2l2gnb2KHXQRgBP6jzdQyzBvPPfiU0aVmUky5gUHTcA',
                'created_at' => '2019-09-11 15:07:03',
                'updated_at' => '2019-09-23 12:39:39',
                'username' => 'D.S.4',
                'user_type' => 'Employee',
                'mobile' => '01882406482',
                'reference_table_id' => 12,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-23 12:39:39',
            ),
            11 =>
            array (
                'id' => 13,
                'name' => 'Chaina Akter',
                'email' => 'shorifislam11@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$eXjI45.iIY.gag/U3H1GUehsT97ezQQ0T01w3j6Owa3IlaGO5waCm',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-11 15:13:34',
                'updated_at' => '2019-09-11 15:13:34',
                'username' => 'A.O.2',
                'user_type' => 'Employee',
                'mobile' => '01922275654',
                'reference_table_id' => 13,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
        ));


    }
}
