<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'সেলিনা পারভেজ',
                'email' => 'salina.pervez@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$.3MZImlq8Q1PNEURn.xikeRI3q4eXJ2lMw76vE04PJi45h6zq5Zcy',
                'is_special' => 0,
                'remember_token' => 'doPouS0DD0kmC683IMhpKwDRQmqc9KPW46rViTkYFiEYq113FMJvfXmwLfKJ',
                'created_at' => '2019-08-27 16:35:38',
                'updated_at' => '2019-08-29 12:14:39',
                'username' => 'JS1',
                'user_type' => 'Employee',
                'mobile' => '01726731208',
                'reference_table_id' => 2,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-08-27 16:42:11',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'গোলাম মোহাম্মদ ভূঁইয়া',
                'email' => 'gmb@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CtuL1cKjVUXPqH4RQpFRBOYyzQsDMrbEgeMJcks6jHW/N8o7KZoLW',
                'is_special' => 0,
                'remember_token' => 'svtG4OS5tuXIaPjz5yGCnuHOfpJKKspMEbyiKHp0ixsPccA28MVLqpDt0qI1',
                'created_at' => '2019-08-27 16:37:08',
                'updated_at' => '2019-08-29 12:16:54',
                'username' => 'DS1',
                'user_type' => 'Employee',
                'mobile' => '01716094068',
                'reference_table_id' => 3,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-08-27 16:44:07',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'ফখর উদ্দীন আহমেদ',
                'email' => 'shakhsadee@hotmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$1LTXnjeFWP1W8YFfnesjqOHT4LBetFFa.WzIT.G4I2h9qrmjKRDGC',
                'is_special' => 0,
                'remember_token' => 'GcU9xIx9KuHEreOimoLo7W4srB9ObUo1dr5AifVapXQ2R3GWfkWwuYYOV881',
                'created_at' => '2019-08-27 16:38:26',
                'updated_at' => '2019-08-29 12:22:21',
                'username' => 'AO1',
                'user_type' => 'Employee',
                'mobile' => '01670688668',
                'reference_table_id' => 4,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-08-27 16:44:41',
            ),
            3 => 
            array (
                'id' => 5,
                'name' => 'মোঃ নবীর উদ্দীন',
                'email' => 'nobir@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$NBVWXyXphbfWNbk7yoK6puy5PaPKXxYcDFR4I2v0VTcmYJ/Z6WEzy',
                'is_special' => 0,
                'remember_token' => 'qXr8aSuHJQOHd4qITbMhq7hgscUtwrt1XZGazjeVTV6ivZ46j89BvBZ2MRIm',
                'created_at' => '2019-08-27 18:59:27',
                'updated_at' => '2019-08-29 12:28:42',
                'username' => 'ME1',
                'user_type' => 'Employee',
                'mobile' => '01717178030',
                'reference_table_id' => 5,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-08-27 18:59:58',
            ),
            4 => 
            array (
                'id' => 6,
                'name' => 'মোঃ খায়রুল আমীন',
                'email' => 'khairul.amin@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$/uY1AsMVOUCDoAVZFGOwRezPn3keOSj4WVfbbw6taphgLHEMIzaWe',
                'is_special' => 0,
                'remember_token' => 'PkePtS7OQiE6LlEYzpoQkbgAbO6Z0jqqhpkHPzCQkNUOEHnM75gw3Ql2UJcv',
                'created_at' => '2019-09-11 14:34:40',
                'updated_at' => '2019-09-11 16:18:06',
                'username' => 'J.S.1',
                'user_type' => 'Employee',
                'mobile' => '01727674265',
                'reference_table_id' => 6,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-11 16:18:06',
            ),
            5 => 
            array (
                'id' => 7,
                'name' => 'মোঃ আবদুস সাত্তার সরকার',
                'email' => 'ssarker@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$pnA7KOMbixMW8lzTpAFaf.KtXWhF/rwsnLI/vuLKuqP446TdtuE.G',
                'is_special' => 0,
                'remember_token' => 'e0eanPS3lWyae2nn5dda4FpbBJ8vL4mqFH4AGXY0snxrUqOtnvDoEsDMyYDd',
                'created_at' => '2019-09-11 14:40:01',
                'updated_at' => '2020-01-06 16:03:52',
                'username' => 'J.S.2',
                'user_type' => 'Employee',
                'mobile' => '01550150635',
                'reference_table_id' => 7,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2020-01-06 16:03:52',
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'মোঃ আমজাদ হোসেন বেপারী',
                'email' => 'amjadbapari@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$B01p595DLstCMcT7hbHSy.8Qw1iu0p0sY47CByVnizJoO4r.WVkBi',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-11 14:43:14',
                'updated_at' => '2019-09-11 14:43:14',
                'username' => 'J.S.3',
                'user_type' => 'Employee',
                'mobile' => '01711909766',
                'reference_table_id' => 8,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'এহছানুল পারভেজ',
                'email' => 'parvez770@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$jIPbM8MYRHfhFjtBA.kPa.WpNZ3eozYkKyLmj5Y9lLiphYiVjRqBO',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-11 14:45:59',
                'updated_at' => '2019-09-11 14:45:59',
                'username' => 'J.S.4',
                'user_type' => 'Employee',
                'mobile' => '01715087778',
                'reference_table_id' => 9,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'name' => 'ড. মুহম্মদ মেহেদী হাসান',
                'email' => 'mehedi@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$0XULez8TTZB1bRpLeSXq/eVTTDHRkCVIX6vlLT5upy3drIww4lfcS',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-11 14:54:42',
                'updated_at' => '2019-09-11 14:54:42',
                'username' => 'D.S.2',
                'user_type' => 'Employee',
                'mobile' => '01552476487',
                'reference_table_id' => 10,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'name' => 'মোঃ মাইনুল হক ভূঁইয়া',
                'email' => 'moynul@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$BCPs/nqbAJwx/lhquX5iTO4c1mAgPW0ZkwpnNRhHPWgzYfBGvMW7a',
                'is_special' => 0,
                'remember_token' => '7xduU0LDtNcSBFG940Odrw4CAOfjDcuOMCf2pi1EzwCsHeA869xNwKgzDq2y',
                'created_at' => '2019-09-11 15:03:05',
                'updated_at' => '2019-09-11 17:25:00',
                'username' => 'D.S.3',
                'user_type' => 'Employee',
                'mobile' => '01711385917',
                'reference_table_id' => 11,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-11 17:25:00',
            ),
            10 => 
            array (
                'id' => 12,
                'name' => 'মোঃ মনিরুল ইসলাম',
                'email' => 'monirul@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$FE/y0r1gI9RmeHbBVofTsevGmwD0mDAA4ja.tnnSjj3AlXwkU7Ipa',
                'is_special' => 0,
                'remember_token' => '6O4GJDWpNKkOxpGzG2l2gnb2KHXQRgBP6jzdQyzBvPPfiU0aVmUky5gUHTcA',
                'created_at' => '2019-09-11 15:07:03',
                'updated_at' => '2019-09-23 12:39:39',
                'username' => 'D.S.4',
                'user_type' => 'Employee',
                'mobile' => '01882406482',
                'reference_table_id' => 12,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-23 12:39:39',
            ),
            11 => 
            array (
                'id' => 13,
                'name' => 'মোঃ শরিফুল ইসলাম',
                'email' => 'shorifislam11@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$eXjI45.iIY.gag/U3H1GUehsT97ezQQ0T01w3j6Owa3IlaGO5waCm',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-11 15:13:34',
                'updated_at' => '2019-09-11 15:13:34',
                'username' => 'A.O.2',
                'user_type' => 'Employee',
                'mobile' => '01922275654',
                'reference_table_id' => 13,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'চায়না আক্তার',
                'email' => 'rimimoict@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$CSnGtpBrH.6ovHlhJHi08uDq4DlBVcgH2uPM.F/3Q0Oexs7qSHhQS',
                'is_special' => 0,
                'remember_token' => '3NFZtmGVr9kGYNaRFSDXGvghR80oufIWNffXSYvWhKC3DS7WxL2xb1sf41XM',
                'created_at' => '2019-09-11 15:15:59',
                'updated_at' => '2019-09-11 15:49:55',
                'username' => 'A.O.3',
                'user_type' => 'Employee',
                'mobile' => '01923410711',
                'reference_table_id' => 14,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-11 15:49:55',
            ),
            13 => 
            array (
                'id' => 15,
                'name' => 'মল্লিক মনিরুল ইসলাম',
                'email' => 'mmikanta@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$lbUwfmW9HecibSO6t5ynsePA/5VLYyMyg.Nd.Peyk/lyXAL6qlkVq',
                'is_special' => 0,
                'remember_token' => 'OQ8D6wioVVyadCb1f3vUAp2rPJCOV67nc2EwvUzbx5jjebjsILNZIkQqtWPt',
                'created_at' => '2019-09-11 15:19:50',
                'updated_at' => '2019-09-11 15:33:52',
                'username' => 'CASH',
                'user_type' => 'Employee',
                'mobile' => '01911468379',
                'reference_table_id' => 15,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-11 15:33:52',
            ),
            14 => 
            array (
                'id' => 16,
                'name' => 'মোঃ বুলবুল ইসলাম',
                'email' => 'mdbulbulislam81@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$.41nNfBoRJzAUJSJhkDmyORjlTXZ1on04sFKxf9eMploMmj9lC3.K',
                'is_special' => 0,
                'remember_token' => 'NfNvGOmpRKCOR26UZWRLXGpXT52R7jOdidGosV612oAytGki0PHEdF3W6Ejj',
                'created_at' => '2019-09-11 15:22:32',
                'updated_at' => '2019-09-11 17:09:50',
                'username' => 'CASHSOR',
                'user_type' => 'Employee',
                'mobile' => '01912282948',
                'reference_table_id' => 16,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-11 17:09:50',
            ),
            15 => 
            array (
                'id' => 17,
                'name' => 'মোঃ আখতারুজ্জামান',
                'email' => 'mail@mail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$cwbPagDMF7uR4mYjwDvFUeA0CPUbcILO7Yk7ixg/0rOtMkYNBZmmi',
                'is_special' => 0,
                'remember_token' => 'nmLpdMFWyNSy0K73Y0TiWzF8FCV1V0TmQmn1h6xxLfd1e18alz0b781kwWuD',
                'created_at' => '2019-09-11 19:22:15',
                'updated_at' => '2019-09-14 22:40:12',
                'username' => 'JS5',
                'user_type' => 'Employee',
                'mobile' => '01715016422',
                'reference_table_id' => 17,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-14 22:40:12',
            ),
            16 => 
            array (
                'id' => 18,
                'name' => 'ড. মোঃ ফজলুর রহমান',
                'email' => 'fazlu@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$z1KUfyj/MPMgiSVJVhTW7.L9i4GvXVZip4YtzI0hU04ZuAdcRZDny',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-12 11:30:45',
                'updated_at' => '2019-09-12 11:30:45',
                'username' => 'JS6',
                'user_type' => 'Employee',
                'mobile' => '01716123541',
                'reference_table_id' => 18,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            17 => 
            array (
                'id' => 19,
                'name' => 'আবু আহমদ ছিদ্দীকী',
                'email' => 'siddique@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$z1EuDw0wxUeL9k.h0hb5/u/mfRLXe0M1uH5gTYNjxlAr596egu6oC',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-12 11:43:11',
                'updated_at' => '2019-09-12 11:43:11',
                'username' => 'JS7',
                'user_type' => 'Employee',
                'mobile' => '01550153746',
                'reference_table_id' => 19,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            18 => 
            array (
                'id' => 20,
                'name' => 'মোছাঃ আসপিয়া আকতার',
                'email' => 'aspia@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$4sd5Qiz6hfbsH2pZ9Xt9dOsCVmAkMpWJOLYN68lH1QCGATyZnYjdO',
                'is_special' => 0,
                'remember_token' => 'C3knL0iDjiBmu1G7ndtz5k6UkMFZuPRl4puOXHXZNfKNPd1fFUB6okI39iY8',
                'created_at' => '2019-09-12 11:50:33',
                'updated_at' => '2019-09-14 22:33:57',
                'username' => 'DCH',
                'user_type' => 'Employee',
                'mobile' => '88028121150',
                'reference_table_id' => 20,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-14 22:33:57',
            ),
            19 => 
            array (
                'id' => 21,
                'name' => 'রাজা মুহম্মদ আব্দুল হাই',
                'email' => 'raza6676@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$QxX2uSYF6Pb0ommlcr/TYu7T8eSfmcRjKUAX8TdcGUB7twLTiTjyO',
                'is_special' => 0,
                'remember_token' => 'kbFSmWZsmpc7YDq4cWX8q0XGl3Z61RTxiGyhVudbhdF3aMVCVae94hXyNZap',
                'created_at' => '2019-09-12 11:55:49',
                'updated_at' => '2019-09-12 15:29:33',
                'username' => 'DS5',
                'user_type' => 'Employee',
                'mobile' => '01710873246',
                'reference_table_id' => 21,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-12 15:29:33',
            ),
            20 => 
            array (
                'id' => 22,
                'name' => 'সালমা সিদ্দিকা মাহতাব',
                'email' => 'salma.siddiqa@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$nAdzB19CV10pqYAZNWf/l.xkOvQznQkwRpvi1eKfqTJ.e/DW.06Iy',
                'is_special' => 0,
                'remember_token' => 'fMsM7FumOr27W2McaST7aRwUPtgcILSt8U8gTVmCBhMjj4YV1JybuQaD8oXa',
                'created_at' => '2019-09-12 12:05:59',
                'updated_at' => '2019-09-12 15:47:42',
                'username' => 'DS6',
                'user_type' => 'Employee',
                'mobile' => '01714448369',
                'reference_table_id' => 22,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-12 15:47:42',
            ),
            21 => 
            array (
                'id' => 23,
                'name' => 'হাসিনা বেগম',
                'email' => 'hasina@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$3Xt6tOnPi77AlOe4eS..zuwPuZIfiW6gLTT5HNeVdVEfdZP45lRDi',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-12 12:10:46',
                'updated_at' => '2019-09-12 12:10:46',
                'username' => 'DS7',
                'user_type' => 'Employee',
                'mobile' => '01717122779',
                'reference_table_id' => 23,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            22 => 
            array (
                'id' => 24,
                'name' => 'মোঃ সাবেত আলী',
                'email' => 'sabet@ictd.gov.bd',
                'email_verified_at' => NULL,
                'password' => '$2y$10$sg4EtkkyjSg33SbOSIURBeAgBWTpIea8O82TUMHJHHQSJRHTxebKG',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-12 12:16:53',
                'updated_at' => '2019-09-12 12:16:53',
                'username' => 'DS8',
                'user_type' => 'Employee',
                'mobile' => '01712507730',
                'reference_table_id' => 24,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            23 => 
            array (
                'id' => 25,
                'name' => 'ইসরাত অনামিকা',
                'email' => 'anamicaisrat@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$D0MQTQF6qFpLoQBSNE7SJOuw9K7J6ujK9mCXDg3QRQ44ueub0xBLK',
                'is_special' => 0,
                'remember_token' => 'bgKcJPvP7rZsXFrEMfAMyFaitMSPvZAFFn9rfzgTbJa58I4gjO8l4kZDnLTT',
                'created_at' => '2019-09-12 12:19:29',
                'updated_at' => '2019-09-12 15:09:53',
                'username' => 'AO4',
                'user_type' => 'Employee',
                'mobile' => '01515298562',
                'reference_table_id' => 25,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-12 15:09:53',
            ),
            24 => 
            array (
                'id' => 26,
                'name' => 'নুছরাত জাহান',
                'email' => 'nusratictd@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$sWnd3rSHTbnP/WbInQDARuxhihxPtpmcYCHur1lQzcnEWoPFNk2Xi',
                'is_special' => 0,
                'remember_token' => 'rpOehrRh3aEokdVUxasFnIuESHph5g6wkDYhYsRjh2eNKppv6dN5KUysh92k',
                'created_at' => '2019-09-12 12:27:38',
                'updated_at' => '2019-09-12 15:33:50',
                'username' => 'AO5',
                'user_type' => 'Employee',
                'mobile' => '01712498535',
                'reference_table_id' => 26,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-12 15:33:50',
            ),
            25 => 
            array (
                'id' => 27,
                'name' => 'মোঃ মিনহাজ হোসেন',
                'email' => 'minhajhossain11@yahoo.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$d29RBriLhyHT50PCJAzveeV7Uf1im7myBXkSPR7j4kUn4dVlfFv32',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-12 12:35:42',
                'updated_at' => '2019-09-12 12:35:42',
                'username' => 'AO6',
                'user_type' => 'Employee',
                'mobile' => '01760407187',
                'reference_table_id' => 27,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            26 => 
            array (
                'id' => 28,
                'name' => 'নাজনীন সুলতানা',
                'email' => 'mdnazid9@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$NCe58B9oEhZi0WXlbvuk.OkNXC8jp8i7WsXeSl8XTxJ/cwZ23ru9m',
                'is_special' => 0,
                'remember_token' => '08ZChZjmbtaxX1zr8NFTJ3aZziolj8XLEpzH77buON2OBclvPgQiwJTMEf6L',
                'created_at' => '2019-09-12 13:10:00',
                'updated_at' => '2019-09-12 15:25:51',
                'username' => 'COMPOP1',
                'user_type' => 'Employee',
                'mobile' => '17123456789',
                'reference_table_id' => 28,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-12 15:25:51',
            ),
            27 => 
            array (
                'id' => 29,
                'name' => 'ফরিদা আক্তার মিষ্টি',
                'email' => 'mail1@mail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$05Dapnqw.3L1mQcIQH5jVu7650rfA/5HMxptN/qp1NycpY2GDSJE2',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-12 13:31:52',
                'updated_at' => '2019-09-12 13:31:52',
                'username' => 'OACCO',
                'user_type' => 'Employee',
                'mobile' => '01684913229',
                'reference_table_id' => 29,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            28 => 
            array (
                'id' => 30,
                'name' => 'আহম্মেদ আলী',
                'email' => 'ahmmedmanik@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$FQGznKKG0fp66HAwk1hOg.ZOvzLBOwQilnzY7HwGN24K3dSs8PwZC',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-12 13:36:45',
                'updated_at' => '2019-09-12 13:53:34',
                'username' => 'OACCO1',
                'user_type' => 'Employee',
                'mobile' => '01710795768',
                'reference_table_id' => 30,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            29 => 
            array (
                'id' => 31,
                'name' => 'মো: হযরত আলী',
                'email' => 'hazrat448@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$iiV9T22ieaOM8kYlsq7k0eAp3KhUbQg8gOM0LZ45BWKZJbvvcvaEK',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-12 13:39:49',
                'updated_at' => '2019-09-12 13:52:55',
                'username' => 'OACCO2',
                'user_type' => 'Employee',
                'mobile' => '01743958644',
                'reference_table_id' => 31,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            30 => 
            array (
                'id' => 32,
                'name' => 'ছানোয়ার হোসেন',
                'email' => 'sanowarinfo@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$J958koCLBYQo05XP5Vc1hu6d6xlOZNLf9SR75QJn8Yahc7XvQOnje',
                'is_special' => 0,
                'remember_token' => 'FX9BCIkzQ8kiZOkqITD3ABl4sdRqklpjvDK5gc3jxQRLvpVR43bMCPHteJ00',
                'created_at' => '2019-09-12 13:42:02',
                'updated_at' => '2019-09-12 15:44:28',
                'username' => 'OACCO3',
                'user_type' => 'Employee',
                'mobile' => '01719787366',
                'reference_table_id' => 32,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-12 15:44:28',
            ),
            31 => 
            array (
                'id' => 33,
                'name' => 'মো: সফিকুল ইসলাম',
                'email' => 'hridoyictd@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$.oePKvZKeFwgRbXKIWJFJOSoGuy1lNRpJbAEwxAvoOqhwC6xF0U66',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-12 13:47:20',
                'updated_at' => '2019-09-12 13:51:38',
                'username' => 'OACCO4',
                'user_type' => 'Employee',
                'mobile' => '01682953737',
                'reference_table_id' => 33,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            32 => 
            array (
                'id' => 34,
                'name' => 'শাহিনা আক্তার',
                'email' => 'shahinaictd@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$8ppsJC8HRV2jL7CYtBziGeeU2qFRWi65SyrE8/CJzQyAQE6jJdFYO',
                'is_special' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-12 13:49:54',
                'updated_at' => '2019-09-12 13:49:54',
                'username' => 'OACCO5',
                'user_type' => 'Employee',
                'mobile' => '01779292751',
                'reference_table_id' => 34,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => NULL,
            ),
            33 => 
            array (
                'id' => 35,
                'name' => 'মোঃ শহিদুল ইসলাম',
                'email' => 'mail7@mail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Vdih5GCWLKXH5IFeQwQ.tuqUvRmy.hyOZggZAssXr0fDRLWdzBpx6',
                'is_special' => 0,
                'remember_token' => 'Wkx36mqDHsmrFRLx7QXUDqQ8EU88urknNgZWqmq6LNTcpVwkyAaeoSSLjFmR',
                'created_at' => '2019-09-12 14:26:07',
                'updated_at' => '2019-09-12 15:13:18',
                'username' => 'OACCO6',
                'user_type' => 'Employee',
                'mobile' => '01743259555',
                'reference_table_id' => 35,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-09-12 15:13:18',
            ),
            34 => 
            array (
                'id' => 36,
                'name' => 'তোফাজ্জল হোসেন',
                'email' => 'acr.mopa@inflack.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$RkHQ5g4FtxwIQjlsfEmuiuUX2sCsMVWt6I/6rgNdfDGwoJW2ZWH3e',
                'is_special' => 0,
                'remember_token' => 'S7f6PC0MIyM4qK0XlYJYGEUbDjdGdLfF4uhh8o9h8mp5VZpcjWUcf9IAD4uE',
                'created_at' => '2019-12-22 10:16:13',
                'updated_at' => '2019-12-22 10:21:52',
                'username' => 'JSM',
                'user_type' => 'Employee',
                'mobile' => '017112233456',
                'reference_table_id' => 36,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-12-22 16:21:52',
            ),
            35 => 
            array (
                'id' => 37,
                'name' => 'মোসাম্মৎ লায়লাতুল ফেরদৌস',
                'email' => 'mail2@mail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Vf6arwoDz6I8VQgg9zUAPOVq9gSNvZ1rdXptceKPGlmm4hGxtDK4O',
                'is_special' => 0,
                'remember_token' => '65NS7g1tWDwskS77Ha3EZIqsnzoXOKIEnUW1ekuZLeLTXtOfCmXwXihoXG89',
                'created_at' => '2019-12-22 10:25:47',
                'updated_at' => '2019-12-22 13:59:04',
                'username' => 'DSM',
                'user_type' => 'Employee',
                'mobile' => '017112233457',
                'reference_table_id' => 37,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-12-22 19:59:04',
            ),
            36 => 
            array (
                'id' => 38,
                'name' => 'ইসমাইল হোসেন',
                'email' => 'mail3@mail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$vOwVVKRIahyk2j4LK.ZXUeq/iD04kKjAETWzIur7ymuyg9ECJZXhq',
                'is_special' => 0,
                'remember_token' => 'aw137TA5NOuJVhvMBTtMJt2BH8BxWp7Ryntzh9kst3P5OIx5bd0998uZJ9ec',
                'created_at' => '2019-12-22 10:31:03',
                'updated_at' => '2019-12-22 10:42:22',
                'username' => 'OACO',
                'user_type' => 'Employee',
                'mobile' => '017112233458',
                'reference_table_id' => 38,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-12-22 16:42:22',
            ),
            37 => 
            array (
                'id' => 39,
                'name' => 'হেলাল উদ্দিন',
                'email' => 'mail4@mail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Tv2nCnXAnxxWeBneXpv24ucWE594Zo8RuUtNIO0iY0TFk9cnr8Wy2',
                'is_special' => 0,
                'remember_token' => 'rLa5W4pM3b1qg7I2lECSjhAwKoGQxMmqaGAI1AE52nyR7O0n6fvIF5Gh64om',
                'created_at' => '2019-12-22 10:37:23',
                'updated_at' => '2019-12-22 10:42:55',
                'username' => 'AOM',
                'user_type' => 'Employee',
                'mobile' => '017112233459',
                'reference_table_id' => 39,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2019-12-22 16:42:55',
            ),
            38 => 
            array (
                'id' => 40,
                'name' => 'শেলিনা খানম',
                'email' => 'mail5@mail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$FFvHx4qoSsIWIZbBiqddK.qH.XcrC75zhDc4dHbn77OCUctr9vZ4.',
                'is_special' => 0,
                'remember_token' => 'BgyJK7BHPPNMJFpgvqvyw0QrtqiMgSlHRAdIprbRZ53VOgyROOxxxh7bFkmq',
                'created_at' => '2019-12-22 14:52:30',
                'updated_at' => '2020-01-05 11:23:15',
                'username' => 'SYSA',
                'user_type' => 'Employee',
                'mobile' => '017112233450',
                'reference_table_id' => 40,
                'status' => 'Active',
                'deleted_at' => NULL,
                'last_password_change' => '2020-01-05 17:23:15',
            ),
        ));
        
        
    }
}